### PR TITLE
Updated build system to use gradle

### PR DESCRIPTION
**Pull request by f41c0r**
Google moved to Android-Studio and Gradle in 2013... So 2 years ago.

Screenshot of the app working fine off my build:
adb-screenshot-2015-08-20-12-24-16-913067076

### CODE REVIEW

**Comment by zagaberoo** [comment]
I appreciate your desire to keep Diode up with the times, but it is not an accident that Diode still uses Ant.  Believe it or not, I actually prefer it.

**Comment by f41c0r** [comment]
Okay, I'm forking

**Comment by zagaberoo** [comment]
By all means; that's the beauty of FOSS!

**Comment by f41c0r** [comment]
No hard feelings, I'd rather break compatibility with older devices and keep a modern codebase than vice-versa

**Comment by zagaberoo** [comment]
I meant my last comment genuinely: the beauty of software libre is we can have it both ways.

Ant vs Gradle doesn't really come into compatibility with older devices, but legacy support is a major goal of Diode as a project.

Personally, I use a more modern and actively developed FOSS reddit client you might want to check out: [RedReader](https://play.google.com/store/apps/details?id=org.quantumbadger.redreader).

**Comment by f41c0r** [comment]
HUH. Well. I'll have to give it a shot then - my main complaint was that the UI was old and the HTTPS issue. Thanks for the heads up

**Pull request closed without merging**
