### PR TITLE
Adds the 'Go to thread' option to comments on users' profiles. 

### PR DESCRIPTION
**Pull request by Protuhj**
Also makes it so to 'Go to comment' goes to the comment with context.

### CODE REVIEW

**Comment by zagaberoo** [comment]
That was quick.  I'm working on another project tonight, but I'll take a look at this tomorrow and then roll it into an update in a week or so.

**Comment by Protuhj** [comment]
No worries, this isn't a high priority thing, just a QOL change.

**Comment by Protuhj** [comment]
By the way, to test: just go to your profile, and click on one of your comments.  

I tested it with comments that were in huge threads, to make sure the context worked as it should.

**Comment by zagaberoo** [comment]
Looks good.

I think to avoid confusion there needs to be a visual indicator that the thread you're viewing isn't the whole thread.  Something vaguely like this: 
image

**Comment by Protuhj** [comment]
I was thinking the same thing this morning, actually.

**Comment by Protuhj** [comment]
And in all honesty, I don't have much experience with creating an Android UI, I don't know if I can create a UI element that doesn't look like a child made it.

**Comment by zagaberoo** [comment]
No worries; I'm up for taking care of that aspect in this case.

**Comment by Protuhj** [comment]
I got the UI element working locally - I can create a branch separate from this pull request if you want to view what I have so far..

I have it going to the full comments thread when you click on it, I'm thinking about adding the "view parent thread" and the "view full context" items that you can do in reddit.

**Comment by zagaberoo** [comment]
Sounds good to me

**Comment by Protuhj** [comment]
I'm working on wiring up the logic so all that you'll need to look at is the UI element.

BTW -- I made the element semi-transparent so you can tell when you're clicking and long-pressing on it. Otherwise, the color wouldn't come through.

**Comment by Protuhj** [comment]
Ok -- created a branch here: https://github.com/Protuhj/diode/tree/context_update  

A light-theme UI element needs to be created, but once you fix/change the current one, that shouldn't be difficult to add. 

Also, I use IntelliJ, so you might need to update your project file to include the new UI file.

**Comment by zagaberoo** [comment]
Merged!  Looks good; I would have done a very similar look.

I think I may have thrown you under the git bus when I cherry picked your last pull request.  I groomed the history to remove the merge artifacts and to squash your astyle reformat into the functional change commit.  Your net contributions and commit attributions are still identical though, don't worry.

Because I groomed the history, please abandon your branches to avoid further git madness.  In fact, if you don't have other local changes, it would be easiest to just delete your working directory and re clone.

If you do have other local changes and need help wrangling git, please let me know since I'm the root of the confusion.

**Comment by Protuhj** [comment]
I'll re-fork/re-clone everything.  

(I'm used to Subversion and Mercurial, I don't have a lot of Git experience)

**Pull request closed without merging**
