### PR TITLE
Properly loads the context of a comment if context is asked for.

### PR DESCRIPTION
**Pull request by Protuhj**
When using the 'Go to comment' menu item in your inbox, it is supposed to go to the context, this fixes that functionality by using the proper API call.

### CODE REVIEW

**Comment by zagaberoo** [comment]
Merged.  I cherry picked it so github's a little confused, but it's in there.  It's getting pushed out to GP as part of version 1.1.4 as we speak.

Thanks for contributing!

**Comment by Protuhj** [comment]
No problem, I've been using this app for a long time, and still prefer it over more "pretty" apps.

This doesn't address the problem of going to someone's profile and hitting the 'Go to comment' menu option there. I'm working on a 'fix' for that as well.

**Comment by zagaberoo** [comment]
I'm glad you're still enjoying it; you're one of about 7,000 at this point.

I look forward to accepting your patch.

**Comment by Protuhj** [comment]
I'm working on getting AStyle set up over here to get rid of any whitespace/formatting issues.

**Comment by zagaberoo** [comment]
I assume you saw my commit doing just that on the existing code.

As you may have noticed, the overall style had diverged all over the place and was full of whitespace errors.

Astyle's defaults are now the de facto style rules for the project.  Convention over configuration.

**Comment by Protuhj** [comment]
I saw that -- that was bugging me and my IDE.  We use AStyle at work, but I try to set my IDE up to mirror AStyle's result whereever possible.

**Comment by zagaberoo** [comment]
That's useful to hear.  I dug up astyle this evening with some quick googling and I wasn't sure how prevalent it was.

I couldn't tell you why I didn't autoformat the code when I inherited it, but now it's done.

**Comment by Protuhj** [comment]
We use it on our large C++ project with 20 or so developers being forced to run it on their code before they submit for code review.

**Comment by zagaberoo** [comment]
Always good to have a ground truth to avoid style squabbles.

**Pull request closed without merging**
